### ISSUE TITLE
More explanation on coordinate system File

### ISSUE THREAD

**Issue by jefferyUstc** [rajewsky-lab/openst#47]
Hi openst team, 

when reading the documentations, I found it a little bit confused to understand some terms, like, "the coordinate_system of openst" in the config.yaml. I downloaded the example coordinate system file as below :

```
# download the coordinate system
wget "http://bimsbstatic.mdc-berlin.de/rajewsky/openst-public-data/fc_2_coordinate_system.csv"
```
The file contains contents like below:

```
[jeffery@Jeff puck_data]$ head fc_2_coordinate_system.csv
puck_id,x_offset,y_offset,z_offset
fc_2_L1_tile_1001,0,36282,0
fc_2_L1_tile_1002,0,72564,0
fc_2_L1_tile_1003,0,108846,0
fc_2_L1_tile_1004,0,145128,0
fc_2_L1_tile_1005,0,181410,0
fc_2_L1_tile_1006,0,217692,0
fc_2_L1_tile_1007,0,253974,0
fc_2_L1_tile_1008,0,290256,0
fc_2_L1_tile_1009,0,326538,0
```
are they the x-offset and y-offset of each tile? How can we get this information if we got a different Novaseq S6000 chip?

**Comment by nukappa** [comment]
Hi @jefferyUstc, thanks for the interest in openst!

Yes, the `x_offset` and `y_offset` refer to each tile with the corresponding `puck_id` and they are used to stitch the different tiles together and assemble the sample piece. We've tested different S4 and SP flow cells and found that while the x-offset was the same, the y-offset could differ. That's why we provide two coordinate systems.

If you sequence a flow cell that doesn't adhere to these two types, then you'd have to manually adjust the overall coord system yourself. Aligning the stitched tiles to the HE and inspecting the fiducial markers should be enough for this.

**Comment by jefferyUstc** [comment]
Thank you for your prompt response. 

what's the unit of x-offset and y-offset? is it the same as the [x-pos and y-pos within the tiles](https://rajewsky-lab.github.io/openst/latest/computational/preprocessing_capture_area/#retrieve-spatial-barcodes-coordinates-for-one-tile)? It's unclear what it is.

**Comment by jefferyUstc** [comment]
Hi openst team, btw, you provided two offset files, like 'fc_1_coordinate_system.tsv' and 'fc_2_coordinate_system.tsv', which is for Nova S4 and which is for SP?

**Comment by danilexn** [comment]
Hi Jeffery! Sorry for the late reply.

The units of the coordinate systems are arbitrary (from the Illumina fastq file). To convert to 0.6 micron per unit, you can divide by ~9 (this might be different depending on versions etc).

For the SP flow cell, fc_1 or fc_2 should work just fine. It depends on how the odd columns are offset.

Please let me know if this helped!
