### ISSUE TITLE
Issues in "Fine pairwise alignment (manual)"

### ISSUE THREAD

**Issue by wsyyc** [rajewsky-lab/openst#63]
Hi, 
    I encountered some issues while performing Pairwise alignment following the **E13 mouse head** documentation. I successfully completed the first step and generated the **multimodal/stitched_spots.h5ad** file. 
    However, when I moved to the step of **Fine pairwise alignment (manual)**, I ran into an error. Specifically, in the Qt GUI interface, when I select the all_tiles_coarse layer from the Layer selector and click on Render, I get an error message: **unable to synchronously open object (component not found)**. 
    I Googled this issue and found that it might be related to h5py having trouble reading the h5ad file, I'm not sure how to resolve it. Do you have any suggestions?
Thank you!

**Comment by wsyyc** [comment]
I found that the reason for the error is that my h5 file doesn't contain 'uns/spatial_pairwise_aligned/staining_image_transformed'. However, the previous step, 'Coarse pairwise alignment (auto)', was successful. Do you know what might be causing this issue?

**Comment by danilexn** [comment]
Hi! The latest version of the openst package should not be creating that new image layer. Please make sure you are using v0.1.2, which does not transform the images. Anyway, you can select the image from the file structure using the GUI buttons, and you can select the staining_image (without the _transformed). 

Please let me know if this helps!

**Comment by danilexn** [comment]
Great! That means there's a bug in the `openst from_spacemake` and documentation when it refers to `manual_pairwise_aligner`. I will document and fix this, thanks for noticing it!

The `Coarse pairwise alignment (auto)` is necessary, but in the latest revision only the spatial coordinates, not the image, are transformed. That's why we use the exact same `staining_image` layer. This is useful when you have multiple images from the same FOV (e.g., some IFs), so it is not necessary to transform all of them, just the spatial coordinates (once).

**Comment by wsyyc** [comment]
Thanks for the clarification! I will try it later.
